[mgr]
show_hidden = true
sort_by = "natural"
linemode = "size"

[preview]
max_width = 1800
max_height = 1400
image_delay = 30
image_quality = 75
ueberzug_scale = 1.0
ueberzug_offset = [0.0, 0.0, 0.0, 0.0]
